// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20hlGsrcP3kcDSMT02GkuPu1OGE2AU88',
    appId: '1:37313398389:web:3ab60150ddbb7b440c1a3c',
    messagingSenderId: '37313398389',
    projectId: 'instagram-60de6',
    authDomain: 'instagram-60de6.firebaseapp.com',
    storageBucket: 'instagram-60de6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtc2a0JadGk96hVD2grmxkM6YrWIJ9UR0',
    appId: '1:37313398389:android:6e0bedc75beae8c40c1a3c',
    messagingSenderId: '37313398389',
    projectId: 'instagram-60de6',
    storageBucket: 'instagram-60de6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC36VSN1Ksqa4kcOnEADJ7ZoMx35qr7e1o',
    appId: '1:37313398389:ios:7117aad231d4fa960c1a3c',
    messagingSenderId: '37313398389',
    projectId: 'instagram-60de6',
    storageBucket: 'instagram-60de6.appspot.com',
    iosClientId: '37313398389-4rabfjulbhno64sh57c8omemp8b2ma73.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC36VSN1Ksqa4kcOnEADJ7ZoMx35qr7e1o',
    appId: '1:37313398389:ios:7117aad231d4fa960c1a3c',
    messagingSenderId: '37313398389',
    projectId: 'instagram-60de6',
    storageBucket: 'instagram-60de6.appspot.com',
    iosClientId: '37313398389-4rabfjulbhno64sh57c8omemp8b2ma73.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
